const state={step:0,system:null,values:{BOAT_NAME:'My Boat',BOAT_TYPE:'Motor vessel',BOAT_TIMEZONE:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',BOAT_UNITS:'metric',VESSELSTACK_USER:'boat',SIGNALK_MODE:'docker',SOCKETCAN_ENABLE:'false',AIS_ENABLE:'false',VESSELSTACK_FIREWALL_ENABLE:'false'}};
const panel=document.querySelector('#panel'),status=document.querySelector('#status');
const pages=[
()=>{const s=state.system||{};return `<h2>Preflight at a glance</h2><p class="lead">We’ll create a private configuration file, then hand you the exact install command.</p><div class="grid"><div class="card"><strong>Host</strong>${s.architecture||'Checking…'} · ${s.memory_gib||'?'} GiB RAM<br><span class="${s.docker&&s.compose?'ok':'warn'}">${s.docker&&s.compose?'✓ Docker Compose ready':'! Docker Compose is not ready'}</span></div><div class="card"><strong>Network interfaces</strong>${(s.interfaces||[]).join(', ')||'Checking…'}<br><span class="${s.can0?'ok':'warn'}">${s.can0?'✓ can0 detected':'○ can0 not enabled yet'}</span></div></div><p class="lead">This assistant never changes boot firmware, network rules, or attached marine hardware.</p>`},
()=>`<h2>Hardware checklist</h2><p class="lead">Confirm the dry, fused, serviceable computer installation before software setup.</p><div class="grid">${['Raspberry Pi 5 (8 GB recommended)','High-endurance USB 3 SSD (256 GB+)','Pi 5 active cooling','10–32 V marine DC/DC power supply','Isolated CAN interface for NMEA 2000','Micro-C drop cable and terminated backbone','Ventilated splash-resistant enclosure','Ethernet cable or configured Wi-Fi'].map(x=>`<label class="card"><input type="checkbox"> ${x}</label>`).join('')}</div>`,
()=>`<h2>Name the vessel</h2><p class="lead">Public identifiers are optional and remain on this Pi.</p><div class="grid"><div><label>Boat name</label><input id="BOAT_NAME" value="${state.values.BOAT_NAME}"><label>Boat type</label><input id="BOAT_TYPE" value="${state.values.BOAT_TYPE}"></div><div><label>Timezone</label><input id="BOAT_TIMEZONE" value="${state.values.BOAT_TIMEZONE}"><label>Units</label><select id="BOAT_UNITS"><option value="metric">Metric</option><option value="us_customary">US customary</option><option value="nautical">Nautical</option></select></div></div>`,
()=>`<h2>Storage and service account</h2><p class="lead">Keep data separate from the checkout and backups on removable media.</p><div class="grid"><div><label>Linux service account</label><input id="VESSELSTACK_USER" value="${state.values.VESSELSTACK_USER||'boat'}"><label>Application path</label><input id="VESSELSTACK_ROOT" value="${state.values.VESSELSTACK_ROOT||'/opt/vesselstack'}"></div><div><label>Data path</label><input id="VESSELSTACK_DATA" value="${state.values.VESSELSTACK_DATA||'/opt/vesselstack-data'}"><label>Backup path</label><input id="VESSELSTACK_BACKUP" value="${state.values.VESSELSTACK_BACKUP||'/media/vesselstack-backup/backups'}"></div></div>`,
()=>`<h2>Signal K and NMEA 2000</h2><p class="lead">Use an isolated CAN interface. Enable it only after its vendor overlay is installed and <code>can0</code> appears.</p><label>Signal K installation</label><select id="SIGNALK_MODE"><option value="docker">Install managed Docker Signal K</option><option value="existing">Use an existing Signal K server</option><option value="native">Install native Signal K</option></select><label class="choice"><input id="SOCKETCAN_ENABLE" type="checkbox" ${state.values.SOCKETCAN_ENABLE==='true'?'checked':''}><span><strong>Enable SocketCAN / NMEA 2000</strong>Requires an isolated interface, a correctly powered and terminated backbone, and <code>can0</code> before preflight.</span></label><label>CAN interface</label><input id="SOCKETCAN_INTERFACE" value="${state.values.SOCKETCAN_INTERFACE||'can0'}"><p class="warn">Never power the Pi from two sources. Leave termination disabled on a normal drop connection.</p>`,
()=>`<h2>Optional inputs and network policy</h2><p class="lead">Start small. These can be enabled later by rerunning this wizard.</p><label class="choice"><input id="AIS_ENABLE" type="checkbox" ${state.values.AIS_ENABLE==='true'?'checked':''}><span><strong>USB AIS receiver</strong>Requires a connected receiver under <code>/dev/bus/usb</code>.</span></label><label class="choice"><input id="VESSELSTACK_FIREWALL_ENABLE" type="checkbox" ${state.values.VESSELSTACK_FIREWALL_ENABLE==='true'?'checked':''}><span><strong>Block administration ports on Wi-Fi</strong>Enable only after confirming the interface and an alternate administration path.</span></label>`,
()=>`<h2>Ready to create the configuration</h2><p class="lead">The file is written beside the installer with mode 600. Credentials are generated during installation.</p><div class="grid"><div class="card"><strong>Vessel</strong>${state.values.BOAT_NAME}<br>${state.values.BOAT_TIMEZONE}</div><div class="card"><strong>Data source</strong>Signal K: ${state.values.SIGNALK_MODE}<br>CAN: ${state.values.SOCKETCAN_ENABLE}</div></div><pre>sudo ./install.sh --config vesselstack.env --dry-run\nsudo ./install.sh --config vesselstack.env --start\nsudo vesselstackctl doctor</pre><p>Read <code>docs/INSTALLATION.md</code> before connecting the NMEA backbone.</p>`];
fetch('/api/system').then(r=>r.json()).then(x=>{state.system=x;draw()}).catch(()=>draw());
function sync(){for(const k of ['BOAT_NAME','BOAT_TYPE','BOAT_TIMEZONE','BOAT_UNITS','VESSELSTACK_USER','VESSELSTACK_ROOT','VESSELSTACK_DATA','VESSELSTACK_BACKUP','SIGNALK_MODE','SOCKETCAN_INTERFACE']){const e=document.querySelector('#'+k);if(e)state.values[k]=e.value}for(const k of ['SOCKETCAN_ENABLE','AIS_ENABLE','VESSELSTACK_FIREWALL_ENABLE']){const e=document.querySelector('#'+k);if(e)state.values[k]=e.checked?'true':'false'}}
function draw(){document.querySelector('#steps').innerHTML=pages.map((_,i)=>`<span class="${i<=state.step?'active':''}"></span>`).join('');panel.innerHTML=pages[state.step]();document.querySelector('#back').disabled=state.step===0;document.querySelector('#next').textContent=state.step===pages.length-1?'Save configuration':'Continue';status.textContent=`Step ${state.step+1} of ${pages.length}`}
document.querySelector('#back').onclick=()=>{sync();state.step--;draw()};
document.querySelector('#next').onclick=async()=>{sync();if(state.step<pages.length-1){state.step++;draw();return}status.textContent='Saving…';const r=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:state.values})});const x=await r.json();status.textContent=r.ok?`Saved ${x.saved}`:`Error: ${x.error}`};
draw();
